services:
  - type: web
    name: mybin1
    # oregon: frankfurt
    plan: free
    env: go
    buildCommand: go build -ldflags="-s -w" -tags netgo -trimpath -o mybin1 main.go
    startCommand: ./mybin1